apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: tanzu-build-service
spec:
  vendor: vmware
  title: Tanzu Build Service
  description: Making secure images with Tanzu Build Service
  url: https://github.com/techgnosis/tanzu-edukates
  content:
    image: harbor.lab.home/library/eduk8s-tbs:latest
  duration: 60m
  session:
    namespaces:
      budget: large
    applications:
      terminal:
        enabled: true
      console:
        enabled: true
      editor:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: kpack-user
      rules:
      - apiGroups:
        - kpack.io
        resources:
        - builds
        - builders
        - images
        - sourceresolvers
        verbs:
        - get
        - list
        - watch
        - create
        - delete
        - patch
        - update
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: kpack-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: kpack-user
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)