apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: <my builder>
spec:
  tag: <my registry location>
  serviceAccount: default
  stack: 
    name: <my cluster stack>
    kind: ClusterStack
  store: 
    name: <my cluster store>
    kind: ClusterStore
  order:
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: tanzu-buildpacks/nodejs